import test from 'node:test';import assert from 'node:assert/strict';
import {GetMissionListByUserId} from '../src/libs/missionEnroll.js';
import pool from '../src/utils/pool.js';
import {EnrollMission,PostMissionContents} from '../src/controllers/user/mission.js';
import {GetMissionList} from '../src/libs/mission.js';
import {internalGuard} from '../src/middlewares/internal.js';
import {isWechatVisible} from '../src/utils/wechat.js';
function response(){return {statusCode:200,body:null,status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;}};}
const now=new Date();const earlier=new Date(now.getTime()-86400000*2);const later=new Date(now.getTime()+86400000*3);
const m={missionId:1,isPublic:1,isWechatPublic:1,category:'Culture',maxEnroll:10,enrollStartDate:earlier,enrollEndDate:later,missionStartDate:earlier,missionEndDate:later};
function setup({mission=m,duplicate=false,count=0}={}){const calls=[];const conn={beginTransaction:async()=>calls.push('begin'),commit:async()=>calls.push('commit'),rollback:async()=>calls.push('rollback'),release:()=>calls.push('release'),query:async(sql,args)=>{calls.push({sql,args});if(sql.includes('FOR UPDATE'))return [[{id:1}]];if(sql.includes('FROM mission\n'))return [[mission]];if(sql.includes('AS enrolled'))return [[{enrolled:duplicate?1:0}]];if(sql.includes('AS currentEnrollCount'))return [[{currentEnrollCount:count}]];if(sql.startsWith('INSERT INTO mission_enroll'))return [{insertId:5}];throw new Error('Unexpected SQL');}};pool.getConnection=async()=>conn;pool.query=async(sql,args)=>{calls.push({sql,args});if(sql.includes('oauth_id'))return [[{oauth_id:'wx-user'}]];throw new Error('Unexpected pool query');};return calls;}
function req(body={}){return {params:{missionId:'1'},decoded:{id:3},clientChannel:'wechat_mp',body:{name:'Tester',instagramLink:'https://www.xiaohongshu.com/u/1',wechatId:'wechat-test',visitDatetimeStart:now.toISOString().slice(0,10),visitDatetimeEnd:now.toISOString().slice(0,10),crossborderConsent:true,...body}};}
test('untrusted client cannot select wechat channel; internal routes fail closed',()=>{process.env.INTERNAL_API_KEY='i'.repeat(40);const r={path:'/user/mission/my/1',get:k=>k==='X-Client-Channel'?'wechat_mp':''};internalGuard(r,response(),()=>{});assert.equal(r.clientChannel,'web');const res=response();internalGuard({path:'/internal/mp/login',get:()=>''},res,()=>assert.fail());assert.equal(res.statusCode,401);});
test('visibility always excludes hidden, private and medical missions',()=>{assert.equal(isWechatVisible(m),true);for(const patch of [{isPublic:0},{isWechatPublic:0},{category:'Hospital'},{category:'Massage'}])assert.equal(isWechatVisible({...m,...patch}),false);});
test('consent is mandatory before any database query',async()=>{let queried=false;pool.query=async()=>{queried=true;};const res=response();await EnrollMission(req({crossborderConsent:false}),res,e=>{throw e;});assert.equal(res.body.error.code,'MISSION_NEED_CONSENT');assert.equal(queried,false);});
test('successful enrollment locks mission and stores trusted channel plus server timestamp',async()=>{const calls=setup();const res=response();await EnrollMission(req(),res,e=>{throw e;});assert.equal(res.body.success,true);const insert=calls.find(x=>x.sql?.startsWith('INSERT INTO mission_enroll'));assert.match(insert.sql,/UTC_TIMESTAMP/);assert.equal(insert.args.at(-1),'wechat_mp');assert.ok(calls.indexOf('commit')>calls.indexOf(insert));assert.equal(calls.at(-1),'release');});
test('duplicate/full/hidden/date failures roll back without writing',async()=>{for(const options of [{duplicate:true},{count:10},{mission:{...m,isWechatPublic:0}},{mission:{...m,category:'Hospital'}},{mission:{...m,enrollEndDate:earlier}}]){const calls=setup(options);const res=response();await EnrollMission(req(),res,e=>{throw e;});assert.equal(res.body.success,false);assert.equal(calls.some(x=>x.sql?.startsWith('INSERT')),false);assert.equal(calls.includes('commit'),false);assert.equal(calls.at(-1),'release');}});
test('visit range must stay in mission period',async()=>{const calls=setup();const res=response();await EnrollMission(req({visitDatetimeEnd:'2099-12-31'}),res,e=>{throw e;});assert.equal(res.body.error.code,'INVALID_VISIT_PERIOD');assert.equal(calls.includes('commit'),false);});
test('MP list adds mandatory filters and Chinese search with matching count parameters',async()=>{const queries=[];pool.query=async(sql,args)=>{queries.push({sql,args});return sql.includes('count(id)')?[[{total:0}]]:[[]];};await GetMissionList({channel:'wechat_mp',search:'咖啡',page:1,item:20});for(const q of queries){assert.match(q.sql,/is_wechat_public = 1/);assert.match(q.sql,/NOT IN \('Hospital', 'Massage'\)/);assert.match(q.sql,/title_cn LIKE/);}assert.equal(queries[0].args.length,3);assert.equal(queries[1].args.length,5);});
test('non-selected enrollment cannot submit content',async()=>{pool.query=async(sql)=>{if(sql.includes('FROM mission\n'))return [[{...m,social:'Xiaohongshu',contentStartDate:earlier,contentEndDate:later}]];if(sql.includes('FROM mission_enroll'))return [[{status:'applied'}]];throw new Error('Must not update');};const res=response();await PostMissionContents({...req(),body:{links:{Xiaohongshu:'https://xhslink.com/a'}}},res,e=>{throw e;});assert.equal(res.statusCode,403);assert.equal(res.body.error.code,'MISSION_NOT_SELECTED');});
test.after(async()=>{await pool.end();});

test('WeChat ended list excludes rejected entries in both rows and count',async()=>{const queries=[];pool.query=async(sql,args)=>{queries.push(sql);return sql.includes('COUNT(*)')?[[{totalCount:0}]]:[[]];};await GetMissionListByUserId({page:1,item:10,type:'ended',userId:3,channel:'wechat_mp'});assert.equal(queries.length,2);for(const sql of queries)assert.match(sql,/mission_enroll.status <> 'rejected'/);});
