import {Router} from 'express';
import pool from '../utils/pool.js';
import {LoginCheck} from '../middlewares/auth.js';
import {enabled,templates} from '../utils/notificationPolicy.js';
import * as n from '../libs/notifications.js';
const wrap=fn=>async(req,res,next)=>{try{await fn(req,res);}catch(e){if(['NOT_FOUND','INVALID_VISIT_TIME','INVALID_TIMEZONE','INVALID_COMPLETED_TIME','INVALID_ENROLLMENT_STATUS','ADMIN_REQUIRED','VISIT_ALREADY_COMPLETED','INVALID_BINDING_CODE','INVALID_SUBSCRIPTIONS'].includes(e.message))return res.status(e.message==='NOT_FOUND'?404:400).json({success:false,error:{code:e.message}});next(e);}};
const ok=(res,data)=>res.json({success:true,data});
const available=(req,res,next)=>enabled()?next():res.status(503).json({success:false,error:{code:'NOTIFICATIONS_NOT_CONFIGURED'}});
export const userNotifications=Router();
userNotifications.use(LoginCheck,(req,res,next)=>req.decoded.channel==='wechat_mp'?next():res.status(403).json({success:false}));
userNotifications.post('/signup-choice',wrap(async(req,res)=>{if(!['accepted','declined','deferred'].includes(req.body.decision))return res.status(400).json({success:false});if(process.env.SIGNUP_CONSENT_ENABLED==='true')await pool.query("INSERT INTO user_consent(user_id,purpose,version,choice) VALUES(?,'notifications','2026-09-23',?)",[req.decoded.id,req.body.decision]);ok(res,{});}));
userNotifications.use(available);
userNotifications.get('/config',wrap(async(req,res)=>ok(res,{templates:Object.entries(templates()).map(([kind,t])=>({kind,id:t.id})),adminBound:false})));
userNotifications.post('/subscriptions',wrap(async(req,res)=>{await n.recordSubscriptions(req.decoded.id,req.body.choices,{enrollId:req.body.enrollId,phase:req.body.phase,decision:req.body.decision});ok(res,{});}));
userNotifications.get('/visits/:id',wrap(async(req,res)=>ok(res,await n.visitInfo(req.params.id,{userId:req.decoded.id}))));
userNotifications.put('/visits/:id',wrap(async(req,res)=>ok(res,await n.setVisit(req.params.id,req.body,{userId:req.decoded.id}))));
export const adminNotifications=Router();
adminNotifications.use(available);
adminNotifications.get('/visits/:id',wrap(async(req,res)=>ok(res,await n.visitInfo(req.params.id,{admin:req.admin}))));
adminNotifications.put('/visits/:id',wrap(async(req,res)=>ok(res,await n.setVisit(req.params.id,req.body,{admin:req.admin}))));
